parameters:
#    flowcode_tag.example.class: Flowcode\TagBundle\Example

services:
#    flowcode_tag.example:
#        class: %flowcode_tag.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
