parameters:
#    flowcode_news.example.class: Flowcode\NewsBundle\Example

services:
#    flowcode_news.example:
#        class: %flowcode_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
