<?php

namespace Flowcode\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOrderRepository extends EntityRepository
{
}
