liip_imagine:
    resolvers:
       default:
          web_path:
            web_root: %kernel.root_dir%/../web
            cache_prefix: media/cache

    driver:               gd          
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        main_slider:
            quality: 75
            filters:
                thumbnail: { size: [500, 200], mode: outbound }